version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER?err}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD?err}
    ports:
      - "${MONGODB_PORT?err}:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
